Bottom Navigation with Feed And Settings
AlexGladkov/VkTube-Android pull request #24
Opened 2022-03-21 15:24 UTC by Programistich

Button LogOut From VK in Settings

2022-03-21 15:24 UTC, Programistich commented
Close #21

2022-03-29 13:08 UTC, slartus requested changes
есть замечания

2022-03-29 13:08 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/base/BaseViewModel.kt
> +    fun clearAction(){
с моделью общаемся через Action, поэтому этот метод надо сделать protected или вообще убрать

2022-03-29 13:08 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/navigation/MainBottomNavigation.kt
> +fun shouldShowBottomBar(backStackEntry: NavBackStackEntry?): Boolean {
метод и поле ниже стоит сделать приватными

2022-03-29 13:08 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/settings/SettingsScreen.kt
> +            .padding(horizontal = 16.dp, vertical = 16.dp)
padding(16.dp)

2022-03-29 13:08 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/settings/SettingsScreen.kt
> +                    popUpTo(0)
стоит вынести константу 0 в NavigationTree, например.

2022-03-29 13:08 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/splash/SplashScreen.kt
> +            SplashAction.OpenMain -> navController.navigate(NavigationTree.Root.Feed.name)
OpenMain открывает Feed

2022-04-06 07:18 UTC, mironoff2007 commented
С [Programistich](https://github.com/Programistich) не удалось связаться. Внес комментарии сам, слили в другой ветке. Можно закрыть.

2022-04-06 07:19 UTC, slartus commented
изменения залиты через ветку @mironoff2007

2022-04-06 07:19 UTC, closed without merging