Black list groups
AlexGladkov/VkTube-Android pull request #34
Opened 2022-04-03 16:27 UTC by mironoff2007

Сделал экран со списком игнорирования групп. 
Для перехода на этот экран требуется закончить ButtomNavigation. 
Решил проблему загрузки групп.

2022-04-04 05:27 UTC, slartus requested changes
- Дизайн экрана не красивый - попробуй повторить "Список каналов" из приложения  YouTube
- Стоит назвать этот экран "Список каналов"
- Убрать чекбоксы. Думаю, например, можно в конец Row добавить иконку "Глаз", которая будет вместо чекбокса включать-выключать наблюдение за группами. Или вообще убрать иконки и переключать игнорирование по клику на группу. Альфа-канала, наверное, будет достаточно.

2022-04-04 05:27 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/data/clubs/ClubsRepository.kt
> +    suspend fun fetchClubs(userId: Long, ignoreList: List<Long>? = null): List<GroupsGroupFull> =
ignoreList: List<Long> = emptyList()

2022-04-04 05:27 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/blacklist/GroupsBlackListScreen.kt
> +            onGroupClick = {},
зачем эти пустые реализации?

2022-04-04 05:27 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/blacklist/GroupsBlackListScreen.kt
> +            Size(height * 16 / 9, height)
вынеси это соотношение в константу и примени по всему проекту

2022-04-04 05:27 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/blacklist/GroupsBlackListScreen.kt
> +    val state: LazyListState = rememberLazyListState()
state не применен для LazyColumn

2022-04-04 20:58 UTC, mironoff2007 commented
Внес исправления

2022-04-05 04:23 UTC, slartus requested changes
и смержить с main надо

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/navigation/NavigationTree.kt
> +        Splash, Auth, Main, Detail, BlackListGroups
Здесь тоже надо переименовать в Subscriptions

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/splash/SplashScreen.kt
> +            SplashAction.OpenMain -> navController.navigate(NavigationTree.Root.BlackListGroups.name)
не забудь поменять на Main

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/login/LoginScreen.kt
> +                navController.navigate(NavigationTree.Root.BlackListGroups.name)
не забудь поменять на Main

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +        Icon(
сделай иконке тинт как у шрифта названия группы. имхо, слишком яркая по отношению к остальному контенту

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +            .padding(all = padding.dp)
слишком большое расстояние между группами в списке получается. 16 - horizontal и  4 vertical сделай. и clickable сделай до падддинга

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +        Row(
не понял зачем row в row
Row{
AsyncImage
Text(weight(1f)
Icon
}

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +    if (configuration.orientation == Configuration.ORIENTATION_LANDSCAPE)
зачем разделение на landscape и остальное, если ничего не меняется?

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +data class SubscriptionCellModel(
это должно лежать или отдельно или в файле  ViewModel

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +object SubscriptionListParameters{
private чтобы не засорять эфир

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +fun GroupsGroupFull.mapToSubscriptionCellModel(
переместить туда же где будет SubscriptionCellModel

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +    if (configuration.orientation == Configuration.ORIENTATION_LANDSCAPE)
опять ненужное разделение на положение экрана

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/feed/FeedScreen.kt
> +object FeedViewParameters{
private

2022-04-05 04:23 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +                        name = it.name ?: "",
.OrEmpty()

2022-04-05 06:42 UTC, mironoff2007 commented
Спасибо за комментарии, внес исправления.

2022-04-05 06:52 UTC, slartus requested changes

2022-04-05 06:52 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +            .padding(start= marginLR.dp, end = marginLR.dp, bottom = marginUD.dp, top = marginUD.dp)
1. .padding(horizontal= marginLR.dp, vertical = marginUD.dp)
2. clickable применить до паддинга

2022-04-05 06:52 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +                model.isIgnored = !model.isIgnored
1. isIgnored сделать немутабельной. клик обрабатывать в модели
2. после клика сохранять изменения сразу, а не на back

2022-04-05 13:39 UTC, mironoff2007 commented
Поправил, смерджил с мастером

2022-04-06 01:50 UTC, slartus requested changes

2022-04-06 01:50 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +                isChecked = !isChecked
нет смысла здесь менять isChecked. он не вызовет рекомпозицию. поэтому isChecked надо сделать немутабельным (val)

2022-04-06 01:50 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +                    true -> removeFromIgnore.invoke(model.groupId)
removeFromIgnore и addToIgnore не UI решать) к тому же есть метод toggleIgnore - в нём модель и примет сама решение

2022-04-06 01:50 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/SubscriptionCell.kt
> +                toggleIgnore(model)
метод стоит назвать без указывания логики обработки: onGroupClick. модель сама решит что делать с этой информацией. мы ведь потом можем на клик что-то другое придумать. и придется менять в нескольких местах название

2022-04-06 01:50 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +        viewModel.obtainEvent(SubscriptionsListEvent.ToggleIgnore(item))
сам ивент (и название метода) тоже надо поменять. вьюшка не должна указывать модели что делать - она должна сообщать о том, что произошло

2022-04-06 01:50 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +    fun GroupsGroupFull.mapToSubscriptionCellModel(
экстеншн тут лишний. и посмотри на предмет видимости метода. подозреваю, что можно сделать private

2022-04-06 01:50 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/models/SubscriptionsListEvent.kt
> +    data class ToggleIgnore(val item:SubscriptionCellModel) : SubscriptionsListEvent()
на всякий случай еще раз: add, remove убрать, Toggle поменять название на "ЧтотоПроизошло": ItemClicked или GroupClicked

2022-04-06 19:06 UTC, mironoff2007 commented
Внес комментарии

2022-04-07 02:19 UTC, slartus requested changes

2022-04-07 02:19 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/settings/SettingsScreen.kt
> +            .padding(vertical = spaceBetweenItems.dp)
verticalArrangement = Arrangement.spacedBy(spaceBetweenItems) у родительской Column. и padding horizontal тоже у Column
Item не должен знать что он не один и есть какие-то границы до след. айтема и не должен управлять своим положением в паренте

2022-04-07 07:16 UTC, slartus approved these changes

2022-04-07 07:16 UTC, merged