comments autoload, strings resources refactor
AlexGladkov/VkTube-Android pull request #44
Opened 2022-04-13 20:46 UTC by arnyigor

Автоматически загружаются комменты добавлена только дата коммента(для имени нужен расширенный запрос), рефакторинг зависимостей стринги и утилит, провайдятся отдельно, удалены зависимости от контекста.
P.S. Можно позже добавить снекбар при ошибках запроса на главной(сейчас ничего не показывается, белый экран)

2022-04-14 17:51 UTC, mironoff2007 reviewed
немного комментариев по оформлению

2022-04-14 17:51 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/feed/FeedScreen.kt
> +            .systemBarsPadding()
по-моему тут форматирование съехало

2022-04-14 17:51 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/feed/FeedScreen.kt
> +            LoadingView(previewSize)
и тут

2022-04-14 17:51 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/video/VideoScreen.kt
> +    return (screenHeight - (screenWidth / 16) * 9).coerceAtLeast(screenHeight / 2)
Попрошу вынести в константы, если уж рефакторить.

2022-04-14 17:51 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/video/VideoScreen.kt
>                  modifier = Modifier.padding(horizontal = 16.dp, vertical = 4.dp),
это тоже можно в константы

2022-04-14 17:51 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/video/VideoScreen.kt
>          Column(modifier = Modifier.padding(start = 16.dp)) {
и это

2022-04-14 17:51 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/video/VideoScreen.kt
>              .padding(start = 16.dp, end = 16.dp, bottom = 16.dp, top = 4.dp)
и тут

2022-04-14 17:51 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/video/VideoScreen.kt
>                  modifier = Modifier.padding(top = 8.dp),
и тут

2022-04-14 18:07 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/video/VideoViewModel.kt
> +            viewState = viewState.copy(isLoadingVideo =
Выглядит красиво,  но поменялась логика. Если раньше при false ничего не менялось, теперь изменится на true. Не знаю, скадется ли это на общей логике.

2022-04-14 18:22 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/video/VideoViewModel.kt
> +                viewState.isLoadingVideo?.let { !it } ?: true
Выглядит красиво,  но поменялась логика. Если раньше при false ничего не менялось, теперь изменится на true. Не знаю, скажется ли это на общей логике.

2022-04-15 05:28 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/video/VideoScreen.kt
>                  modifier = Modifier.padding(horizontal = 16.dp, vertical = 4.dp),
выносить паддинги в константы - это лишнее

2022-04-18 07:38 UTC, slartus requested changes

2022-04-18 07:38 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/video/VideoViewModel.kt
> +    private fun updateLoading(loading: Boolean?): Boolean? = when (loading) {
это какой-то не update, а toggle

2022-04-18 07:38 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/utils/DateUtil.kt
> +   private companion object{
https://kotlinlang.org/docs/coding-conventions.html#class-layout
companion идёт последним в классе

2022-04-18 09:54 UTC, mironoff2007 commented
Падает

E/Parcel: Reading a NULL string not supported here.
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mobiledeveloper.vktube, PID: 2814
    java.lang.IllegalArgumentException: The initial value must have an associated anchor.
        at androidx.compose.material.SwipeableState.ensureInit$material_release(Swipeable.kt:138)
        at androidx.compose.material.SwipeableKt$swipeable$3.invoke(Swipeable.kt:594)
        at androidx.compose.material.SwipeableKt$swipeable$3.invoke(Swipeable.kt:573)
        at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:263)
        at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:258)
        at androidx.compose.ui.Modifier$Element$DefaultImpls.foldIn(Modifier.kt:107)
        at androidx.compose.ui.ComposedModifier.foldIn(ComposedModifier.kt:172)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
        at androidx.compose.ui.ComposedModifierKt.materialize(ComposedModifier.kt:258)
        at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke-Deg8D_g(Layout.kt:226)
        at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke(Layout.kt:225)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:302)
        at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:255)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:252)
        at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:110)
        at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1$2.invoke(BottomSheetScaffold.kt:336)
        at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1$2.invoke(BottomSheetScaffold.kt:335)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.BottomSheetScaffoldKt.BottomSheetScaffoldStack-SlNgfk0(BottomSheetScaffold.kt:394)
        at androidx.compose.material.BottomSheetScaffoldKt.access$BottomSheetScaffoldStack-SlNgfk0(BottomSheetScaffold.kt:1)
        at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1.invoke(BottomSheetScaffold.kt:323)
        at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1.invoke(BottomSheetScaffold.kt:322)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1.invoke(BottomSheetScaffold.kt:365)
        at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1.invoke(BottomSheetScaffold.kt:285)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
E/AndroidRuntime:     at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:157)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2270)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2530)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3038)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3024)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3024)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2999)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:709)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1042)
        at android.view.Choreographer.doCallbacks(Choreographer.java:867)
        at android.view.Choreographer.doFrame(Choreographer.java:790)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1029)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:258)
        at android.app.ActivityThread.main(ActivityThread.java:8219)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

2022-04-18 11:14 UTC, arnyigor commented
> Падает, если зайти в видео, где есть комменты.
> 
> E/Parcel: Reading a NULL string not supported here. E/AndroidRuntime: FATAL EXCEPTION: main Process: com.mobiledeveloper.vktube, PID: 2814 java.lang.IllegalArgumentException: The initial value must have an associated anchor. at androidx.compose.material.SwipeableState.ensureInit$material_release(Swipeable.kt:138) at androidx.compose.material.SwipeableKt$swipeable$3.invoke(Swipeable.kt:594) at androidx.compose.material.SwipeableKt$swipeable$3.invoke(Swipeable.kt:573) at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:263) at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:258) at androidx.compose.ui.Modifier$Element$DefaultImpls.foldIn(Modifier.kt:107) at androidx.compose.ui.ComposedModifier.foldIn(ComposedModifier.kt:172) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149) at androidx.compose.ui.ComposedModifierKt.materialize(ComposedModifier.kt:258) at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke-Deg8D_g(Layout.kt:226) at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke(Layout.kt:225) at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116) at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34) at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:302) at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:255) at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107) at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34) at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228) at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:252) at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:110) at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1$2.invoke(BottomSheetScaffold.kt:336) at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1$2.invoke(BottomSheetScaffold.kt:335) at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107) at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34) at androidx.compose.material.BottomSheetScaffoldKt.BottomSheetScaffoldStack-SlNgfk0(BottomSheetScaffold.kt:394) at androidx.compose.material.BottomSheetScaffoldKt.access$BottomSheetScaffoldStack-SlNgfk0(BottomSheetScaffold.kt:1) at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1.invoke(BottomSheetScaffold.kt:323) at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1.invoke(BottomSheetScaffold.kt:322) at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107) at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34) at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1.invoke(BottomSheetScaffold.kt:365) at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1.invoke(BottomSheetScaffold.kt:285) at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116) at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127) E/AndroidRuntime: at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127) at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:157) at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2270) at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2530) at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3038) at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3024) at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252) at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1) at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3024) at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2999) at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:709) at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876) at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107) at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485) at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454) at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34) at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109) at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41) at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1042) at android.view.Choreographer.doCallbacks(Choreographer.java:867) at android.view.Choreographer.doFrame(Choreographer.java:790) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1029) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:258) at android.app.ActivityThread.main(ActivityThread.java:8219) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

Очень странная ошибка.У меня нет ничего.

2022-04-18 11:38 UTC, mironoff2007 commented
Да, странная. Падает только на realme c25s

2022-04-18 11:40 UTC, arnyigor commented
> Да, странная. Падает только на realme c25s

Есть мысли как воспроизвести ошибку или как починить?У меня нет возможности посмотреть на таком телефоне.

2022-04-18 11:48 UTC, slartus commented
сделай заодно чтобы и прокрутка комментов работала

2022-04-18 11:52 UTC, slartus commented
на xiaomi mi 8 тоже не падает, кстати

2022-04-18 12:13 UTC, mironoff2007 commented
> > Да, странная. Падает только на realme c25s
> 
> Есть мысли как воспроизвести ошибку или как починить?У меня нет возможности посмотреть на таком телефоне.

Не знаю как дебажить. Когда заходишь в экран видео, как только отрисовывается коммент, все падает. На эмуле и другом телефоне все норм

2022-04-18 12:15 UTC, arnyigor commented
> > > Да, странная. Падает только на realme c25s
> > 
> > 
> > Есть мысли как воспроизвести ошибку или как починить?У меня нет возможности посмотреть на таком телефоне.
> 
> Не знаю как дебажить. Когда заходишь в экран видео, как только отрисовывается коммент, все падает. На эмуле и другом телефоне все норм

Только новые доработки?Если откатить мои изменения есть падение?

2022-04-18 12:32 UTC, mironoff2007 commented
Коммент, захардкоженный норм отображается в старой версии, но если на него ткнуть, открывается ресайклер комментов и падает, если коммент 1, если много не падает. 
В этой ветке ресайклер не листается. Косяк на реал из мастера повторяется, так что можно решать в другой ветке

2022-04-18 20:38 UTC, mironoff2007 commented
Для BottomSheetScaffold положи sheetContent в Box(Modifier.defaultMinSize(minHeight = 0.dp).fillMaxHeight())

2022-04-19 04:40 UTC, slartus commented
там вообще надо убрать список комментов из боттомшита. список комментов есть всегда - и он под видео (в вертикальном режиме)
а когда тыкаем на "введите текст коммента", то открываем боттом шит с текстовым полем ввода коммента.
мы же ютуп копируем:

https://user-images.githubusercontent.com/1107015/163921367-d9a62265-757f-4466-9add-815d71111d05.mp4

2022-04-20 14:17 UTC, arnyigor commented
> там вообще надо убрать список комментов из боттомшита. список комментов есть всегда - и он под видео (в вертикальном режиме) а когда тыкаем на "введите текст коммента", то открываем боттом шит с текстовым полем ввода коммента. мы же ютуп копируем:
> 
>  6bf42643-2674-45f3-8f1c-0d3eb1499a2e.mp4
ТОже есть такие мысли,что комменты не скролятся из-за BottomSheetScaffold.
Убрать их просто ниже и сделать простым списком?

2022-04-20 14:19 UTC, slartus commented
> > там вообще надо убрать список комментов из боттомшита. список комментов есть всегда - и он под видео (в вертикальном режиме) а когда тыкаем на "введите текст коммента", то открываем боттом шит с текстовым полем ввода коммента. мы же ютуп копируем:
> > 6bf42643-2674-45f3-8f1c-0d3eb1499a2e.mp4
> > ТОже есть такие мысли,что комменты не скролятся из-за BottomSheetScaffold.
> > Убрать их просто ниже и сделать простым списком?

да, комменты сделать списком, а новый коммент в ботомшите

2022-04-21 21:14 UTC, arnyigor commented
> > > там вообще надо убрать список комментов из боттомшита. список комментов есть всегда - и он под видео (в вертикальном режиме) а когда тыкаем на "введите текст коммента", то открываем боттом шит с текстовым полем ввода коммента. мы же ютуп копируем:
> > > 6bf42643-2674-45f3-8f1c-0d3eb1499a2e.mp4
> > > ТОже есть такие мысли,что комменты не скролятся из-за BottomSheetScaffold.
> > > Убрать их просто ниже и сделать простым списком?
> 
> да, комменты сделать списком, а новый коммент в ботомшите

Не получается. Т.к. блок ботомшита перекрывает комметарии. Он же снизу выплывает и блокирует весь контент PaddingValues,

2022-04-21 21:15 UTC, arnyigor commented
> > > > там вообще надо убрать список комментов из боттомшита. список комментов есть всегда - и он под видео (в вертикальном режиме) а когда тыкаем на "введите текст коммента", то открываем боттом шит с текстовым полем ввода коммента. мы же ютуп копируем:
> > > > 6bf42643-2674-45f3-8f1c-0d3eb1499a2e.mp4
> > > > ТОже есть такие мысли,что комменты не скролятся из-за BottomSheetScaffold.
> > > > Убрать их просто ниже и сделать простым списком?
> > 
> > 
> > да, комменты сделать списком, а новый коммент в ботомшите
> 
> Не получается. Т.к. блок ботомшита перекрывает комметарии. Он же снизу выплывает и блокирует весь контент PaddingValues,

Плюс почему-то ломается компаратор на список видео. Хотя модели правильные.

2022-04-22 06:16 UTC, slartus commented
> > > > там вообще надо убрать список комментов из боттомшита. список комментов есть всегда - и он под видео (в вертикальном режиме) а когда тыкаем на "введите текст коммента", то открываем боттом шит с текстовым полем ввода коммента. мы же ютуп копируем:
> > > > 6bf42643-2674-45f3-8f1c-0d3eb1499a2e.mp4
> > > > ТОже есть такие мысли,что комменты не скролятся из-за BottomSheetScaffold.
> > > > Убрать их просто ниже и сделать простым списком?
> > 
> > 
> > да, комменты сделать списком, а новый коммент в ботомшите
> 
> Не получается. Т.к. блок ботомшита перекрывает комметарии. Он же снизу выплывает и блокирует весь контент PaddingValues,

ботомшит перекрывает когда выезжает - всё верно. так и должно быть. посмотри как на прикрепленном видео реализовано в ютуб

2022-04-22 06:17 UTC, slartus commented
> Плюс почему-то ломается компаратор на список видео. Хотя модели правильные.

это не понял. где и когда ломается? при каких словиях?

2022-04-22 06:31 UTC, mironoff2007 commented
У меня тоже ломался компаратор,  я ишью завел.  У меня ломалось при переключении групп в фильтре.  Конкретно когда и почему не копал.

2022-04-22 13:06 UTC, arnyigor commented
> > Плюс почему-то ломается компаратор на список видео. Хотя модели правильные.
> 
> это не понял. где и когда ломается? при каких словиях?

При обычной загрузке.Ничего не менял.Буквально вчера было так.

2022-04-22 13:07 UTC, arnyigor commented
> У меня тоже ломался компаратор, я ишью завел. У меня ломалось при переключении групп в фильтре. Конкретно когда и почему не копал.

Там в компараторе есть группы, возможно они связаны.Типа не хватает данных.

2022-04-22 13:10 UTC, arnyigor commented
> > > > > там вообще надо убрать список комментов из боттомшита. список комментов есть всегда - и он под видео (в вертикальном режиме) а когда тыкаем на "введите текст коммента", то открываем боттом шит с текстовым полем ввода коммента. мы же ютуп копируем:
> > > > > 6bf42643-2674-45f3-8f1c-0d3eb1499a2e.mp4
> > > > > ТОже есть такие мысли,что комменты не скролятся из-за BottomSheetScaffold.
> > > > > Убрать их просто ниже и сделать простым списком?
> > > 
> > > 
> > > да, комменты сделать списком, а новый коммент в ботомшите
> > 
> > 
> > Не получается. Т.к. блок ботомшита перекрывает комметарии. Он же снизу выплывает и блокирует весь контент PaddingValues,
> 
> ботомшит перекрывает когда выезжает - всё верно. так и должно быть. посмотри как на прикрепленном видео реализовано в ютуб

Не совсем ясно.Блок комментариев на видео сделан в контенте ботомшита sheetContent?И у них он скроллится?

2022-04-24 16:49 UTC, mironoff2007 commented
Грузит комменты, отправляет коммент, больше не падает на моем realm. Не грузит аватарку и имя того, кто оставил коммент.

VideoViewModel - "Unowned user" - захардкоженно.  Думаю, можно имя и аватар вставить

2022-04-25 04:55 UTC, slartus requested changes

2022-04-25 04:55 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/comments/CommentsScreen.kt
> +            comments.forEach {
items(comments){
}

2022-04-25 04:56 UTC, slartus commented
комменты всё также не скроллятся.
я предалагаю сделать отдельный ПР "рефакторинг зависимостей стринги и утилит, провайдятся отдельно, удалены зависимости от контекста."
комменты не трогать в этом - сам переделаю

2022-04-25 07:36 UTC, mironoff2007 commented
Скролятся, но криво,  свайпом,  а плавно нет

2022-04-26 09:00 UTC, arnyigor commented
> комменты всё также не скроллятся. я предалагаю сделать отдельный ПР "рефакторинг зависимостей стринги и утилит, провайдятся отдельно, удалены зависимости от контекста." комменты не трогать в этом - сам переделаю

Тогда этот закрыть?

2022-04-26 17:11 UTC, closed without merging