Subscriptions screen improve UI
AlexGladkov/VkTube-Android pull request #48
Opened 2022-05-01 19:07 UTC by mironoff2007

Добавил поле поиска и иконку для того, чтобы менять отметку всего списка подписок целиком

2022-05-04 09:18 UTC, slartus requested changes
есть замечания

2022-05-04 09:18 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +    if (viewState.items != oldItems) {
это во вьюмодели надо делать

2022-05-04 09:18 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +        itemsLocal = viewState.items.filter {
это во вьюмодели делать

2022-05-04 09:18 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +    private fun remove(id: List<Long>) {
странное имя для листа

2022-05-05 05:16 UTC, slartus requested changes
есть замечания

2022-05-05 05:16 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +                viewState = viewState.copy(items = viewState.items),
copy тут лишнее

2022-05-05 05:16 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +                    .contains(searchBy.lowercase(Locale.getDefault()))
searchby.lowercase надо вынести в переменную, чтобы на каждой итерации это не выполнять. а весь метод вынести из майн потока

2022-05-05 05:16 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/models/SubscriptionsListEvent.kt
> +    data class Search(val searchBy: String) : SubscriptionsListEvent()
некорректное название ивента. SearchTextChanged - как-то так. view сообщает о том, что что-то произошло, а не диктует модели что надо делать

2022-05-05 09:15 UTC, slartus requested changes
есть замечания

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +    const val searchFieldPaddingVert = 4
не надо все паддинги выносить.это лишнее и ничем не поможет в читабельности кода. вообще ничему не поможет

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +    sealed class SortBy(){
скобки конструктора лишние.
ты не в андроид студии что ли пишешь? там подсказывает такие вещи. и форматирование тоже

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +    private var sortBy:SortBy = SortBy.NameAndIgnored
форматирование

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +        viewModelScope.launch {
viewModelScope.launch(Dispatchers.Default)

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +        viewModelScope.launch {
и ниже тоже везде такое

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +                val ignoreList = groupsLocalDataSource.loadIgnoreList().toMutableList()
val ignoreList = groupsLocalDataSource.loadIgnoreList() - id

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +                val ignoreList = groupsLocalDataSource.loadIgnoreList().toMutableList()
val ignoreList = groupsLocalDataSource.loadIgnoreList() + id

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +                groupsLocalDataSource.saveIgnoreList(listOf())
groupsLocalDataSource.saveIgnoreList(emptyList())

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/models/SubscriptionsListEvent.kt
> +    object ToggleAll : SubscriptionsListEvent()
ToggleAllClicked

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/models/SubscriptionsListEvent.kt
> +    data class GroupClick(val item: SubscriptionCellModel) : SubscriptionsListEvent()
GroupClicked

2022-05-05 09:15 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/video/VideoScreen.kt
> +
лишняя строка

2022-05-05 13:58 UTC, slartus requested changes
есть замечания.
и я бы поиск и перекллючение игнорирования вынес в отдельные inner классы для разделения ответственности

2022-05-05 13:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +        viewModelScope.launch {
еще раз: или вынеси в viewModelScope.launch(Dispatchers.Default) если хочешь явно указать или вообще убери withContext - viewModelScope.launch итак в Default контексте выполняется

2022-05-05 13:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +            OutlinedTextField(
слишком огромное поле ввода

2022-05-05 13:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +            Icon(
иконку глаза стоит сделать наоборот побольше, 24 наверное или 22

2022-05-05 13:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +            Icon(
и чтобы она была отцентрирована относительно окна поиска

2022-05-05 13:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +        Text(
нет смысла менять высоту:
if (viewState.items.isEmpty(){
   Text()
}

2022-05-05 13:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +            style = TextStyle(color = Fronton.color.textPrimary, fontSize = nothingFoundTextSize.sp),
цвет скорее secondary и положение сделать посередине экрана

2022-05-05 13:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +    sealed class SortBy{
форматирование так и не применено
 Ctrl+Alt+L

2022-05-05 13:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +    sealed class SortBy{
и зачем тут sealed если достаточно enum

2022-05-05 13:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +    private fun toggleAll() {
тоже не на майне делать

2022-05-05 13:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListViewModel.kt
> +    private fun toggleAll() {
как и другие операции со списками ниже

2022-05-05 14:03 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +            OutlinedTextField(
viewModelScope.launch без указания Dispatchers явно выполянется в Main

2022-05-05 14:05 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +            OutlinedTextField(
да, туплю. viewModelScope.launch(Dispatchers.Default){
}

2022-05-06 05:14 UTC, slartus requested changes
замечания + не исправлены предыдущие замечания

2022-05-06 05:14 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +                    .width(searchFieldWidth.dp),
не ширину а высоту надо было уменьшить

2022-05-06 06:37 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +                    .width(searchFieldWidth.dp),
Тогда надо label убрать, а то текст мелкий будет. Я еще в процессе исправления.

2022-05-06 15:46 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +                    .width(searchFieldWidth.dp),
C высотой - фишка филдов компоуза, я так понимаю. Убрать высоту можно только используя BasicTextField, но он не отображает label и icon. Так что поле будет без опознавательных знаков.

2022-05-07 15:56 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +            OutlinedTextField(
не очень понимаю про иннер классы и зачем

2022-05-11 04:52 UTC, slartus requested changes
есть замечания

2022-05-11 04:52 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/splash/SplashScreen.kt
> +            SplashAction.OpenLogin -> navController.navigate(NavigationTree.Root.SubscriptionsList.name)
openlogin открывает подписки?

2022-05-11 04:52 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +    const val searchFieldWidth = 250
нельзя задавать ширину константой. а если экран будет меньше? а если сильно больше?

2022-05-11 11:58 UTC, slartus requested changes

2022-05-11 11:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
> +                    .weight(1f)
не нужен тут вес. и у иконки тоже. ерунда получится. поверни горизонтально-проверь

2022-05-11 11:58 UTC, slartus commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/subscriptions/SubscriptionsListScreen.kt
>                              BorderStroke(2.dp, Fronton.color.textPrimary),
слишком жирный бордер

2022-05-11 12:29 UTC, slartus approved these changes

2022-05-11 12:33 UTC, merged