time ago when video was added
AlexGladkov/VkTube-Android pull request #9
Opened 2022-03-14 22:34 UTC by mironoff2007

Добавил дату. С количеством просмотров не понял, что поправить.

2022-03-15 09:29 UTC, AlexGladkov commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/VideoCell.kt
> +        dateAdded = addingDate?:0,
Просьба соблюдать код-стайл. Буквально парой строчек выше есть пример

2022-03-15 09:30 UTC, AlexGladkov commented on app/src/main/res/values/strings.xml
> +    <string name="ru_10_seconds_ago">секунд назад</string>
Для этого же есть формат строк
https://stackoverflow.com/questions/41950952/how-to-use-android-quantity-strings-plurals

2022-03-15 09:31 UTC, AlexGladkov requested changes
Есть замечания

2022-03-15 22:22 UTC, mironoff2007 commented on app/src/main/res/values/strings.xml
> +    <string name="ru_10_seconds_ago">секунд назад</string>
Теперь знаю, спасибо

2022-03-15 22:29 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/VideoCell.kt
> +        dateAdded = addingDate?:0,
Я так понял, что про пробелы речь? Если да, то моя невнимательность, постараюсь учесть.

2022-03-15 22:33 UTC, mironoff2007 commented
Добавил просмотры, но нет учета падежа, если меньше тысячи (просмотра/просмотров). Если надо это учесть, поправлю позже. Постарался учесть комментарии выше.

2022-03-16 07:24 UTC, Programistich commented on app/src/test/java/com/mobiledeveloper/vktube/ExampleUnitTest.kt
> +        assertEquals(true,true)
А точно нужен нам этот тест?

2022-03-16 08:06 UTC, mironoff2007 commented
Сделал. Постарался учесть комментарии выше.

2022-03-16 09:26 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/VideoCell.kt
> +                    text = "${model.userName} • " +
Я бы вынес в отдельные переменные дату и количество, а потом бы инжектнул

2022-03-16 09:26 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/comments/CommentsScreen.kt
> +        CommentsHeaderView(count = NumberUtil.formatNumberShort(
Тоже бы вынес в отдельную переменную

2022-03-16 09:26 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/utils/NumberUtil.kt
> +    private const val ONE=1
Лучше писать проблемы между знаками 
` private const val ONE = 1`

2022-03-16 09:26 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/utils/NumberUtil.kt
> +        return when (i) {
Можно было сделать переменную для One/two/few
Потому что в when 4 условия и все под капотом одинаковые помимо одного параметра

2022-03-16 09:26 UTC, Programistich commented on app/src/androidTest/java/com/mobiledeveloper/vktube/DateInstrumentedTest.kt
> +        assertEquals(true, true)
Не понимаю зачем тесты, если в конце assert(true, true)
То есть по факту тест всегда пройдет в независимости от тестируемого функционала

2022-03-16 09:26 UTC, Programistich commented on app/src/androidTest/java/com/mobiledeveloper/vktube/NumberFormatInstrumentedTest.kt
> +        val v = NumberUtil.formatNumberShort(
Название переменной v

2022-03-16 09:26 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/VideoCell.kt
>          subscribers = "1.2 тыс подписчиков",
Сходу можно и докинуть плюризацию на подписчиков

2022-03-16 09:26 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/VideoCell.kt
> +                modifier = Modifier
Верни форматирование

2022-03-16 09:26 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/VideoCell.kt
> +            Column(modifier = Modifier
Форматирование

2022-03-16 09:26 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/utils/DateUtil.kt
> +    fun getTimeAgo(unixTime: Int, context: Context? = null): String {
Context null?

2022-03-16 09:26 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/utils/DateUtil.kt
> +        } catch (e: Exception) {
А зачем нужны тут Exception

2022-03-16 09:58 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/VideoCell.kt
> +            Column(modifier = Modifier
наверное, обновления не подтянул, исправлю, не помню чтобы удалял

2022-03-16 09:59 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/ui/common/cell/VideoCell.kt
>          subscribers = "1.2 тыс подписчиков",
Да, можно, но пока не понял откуда они приходят. Потому что это относится к видео, а подписчики к странице/профилю, наверное.

2022-03-16 10:01 UTC, mironoff2007 commented on app/src/androidTest/java/com/mobiledeveloper/vktube/DateInstrumentedTest.kt
> +        assertEquals(true, true)
Да, проходит всегда, смотрю глазами. Тест нужен, чтобы UI не поднимать и другие классы.  Можно сделать, чтобы тесты были валидными.

2022-03-16 11:09 UTC, mironoff2007 commented on app/src/main/java/com/mobiledeveloper/vktube/utils/NumberUtil.kt
> +        return when (i) {
Почему-то 2 для флага two не работает. На эмуляторе не работает few , вроде many тоже. Если не ошибаюсь, это зависит от локали. На телефоне тестовом русский, на эмуле английский. Two будет работать на кокой-то другой типа Чешской, если правильно понимаю. Попробую что-то придумать.

2022-03-16 14:34 UTC, mironoff2007 commented
Внес комментарии

2022-03-16 15:00 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/ui/screens/comments/CommentsScreen.kt
> +    val views = NumberUtil.formatNumberShort(viewState.video?.viewsCount ?:0 , context, R.plurals.number_short_format, R.plurals.views)
пробел после ?:

2022-03-16 15:00 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/utils/DateUtil.kt
> +            ""
Все еще не понимаю зачем тут Exception

2022-03-16 15:00 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/utils/DateUtil.kt
> +    private const val MANY = 99
Вот эти переменные дублируются с другим объектом

2022-03-16 15:00 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/utils/DateUtil.kt
> +                else -> ""
Можно объединить несколько условий в одно как в другом объекте

2022-03-16 16:21 UTC, Programistich commented on .gitignore
> +/.idea/androidTestResultsUserPreferences.xml
:D
Занеси сюда тогда всю папку /.idea, а не только этот файлик

2022-03-16 16:21 UTC, Programistich commented on .idea/.gitignore
> +/.name
Смотри выше комментарий

2022-03-16 16:21 UTC, Programistich commented on app/src/main/java/com/mobiledeveloper/vktube/utils/NumberUtil.kt
> +        val res=context.resources
Пробелы между знаками

2022-03-16 17:11 UTC, mironoff2007 commented on .gitignore
> +/.idea/androidTestResultsUserPreferences.xml
Я это случайно запушил), да добавлю

2022-03-17 07:52 UTC, Programistich commented on .idea/.gitignore
> +/.idea/
Тут вообще ничего менять не нужно, оно же в папке ./idea/
То есть этот файл тоже попадает в игнор

2022-03-17 07:54 UTC, mironoff2007 commented on .idea/.gitignore
> +/.idea/
Да, я это понял уже потом

2022-03-17 12:37 UTC, mironoff2007 commented
Что-то надо еще поправить?

2022-03-17 12:51 UTC, Programistich commented
Я же написал про ./idea

2022-03-17 13:14 UTC, Programistich commented on .idea/.gitignore
>  /workspace.xml
Зачем эти изменения в ветку если ты выше внес папку в гитигнор?

2022-03-17 13:30 UTC, mironoff2007 commented on .idea/.gitignore
>  /workspace.xml
Не знаю как убрать изменения из ветки, когда запушил. По-моему проще создать новый реквест. Извиняюсь, что туплю

2022-03-17 13:32 UTC, closed without merging